'''
MIT License

Copyright (c) 2023 Fast Data Science Ltd (https://fastdatascience.com)

Maintainer: Thomas Wood

Tutorial at https://fastdatascience.com/drug-named-entity-recognition-python-library/

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

'''

common_english_words_to_include_in_drugs_dictionary = {
    "absinthium",
    "acetphenetidin",
    "acetylsalicylate",
    "acocantherin",
    "actinomycin",
    "adrenalone",
    "adrenergic",
    "aerosporin",
    "aloe",
    "amidopyrine",
    "aminopyrine",
    "amphetamine",
    "analeptic",
    "analgesic",
    "andrographolide",
    "anesthetic",
    "angelica",
    "anorectic",
    "antacid",
    "anthelmintic",
    "antiasthmatic",
    "antibiotic",
    "anticholinergic",
    "antidiabetic",
    "antiemetic",
    "antiepileptic",
    "antifibrinolysin",
    "antihemorrhagic",
    "antihistamine",
    "antimalarial",
    "antiparasitic",
    "antipruritic",
    "antipyretic",
    "antispasmodic",
    "apomorphine",
    "arbutin",
    "arecoline",
    "aspirin",
    "atebrin",
    "atropine",
    "aureomycin",
    "bacitracin",
    "barbital",
    "barbitone",
    "barosmin",
    "belladonna",
    "benzocaine",
    "benzofuran",
    "benzoin",
    "benzylpenicillin",
    "berbamine",
    "betulin",
    "bicarbonate",
    "biguanide",
    "bioral",
    "biotin",
    "bismuth",
    "boldo",
    "borneol",
    "bronchodilator",
    "butyrolactone",
    "calamus",
    "camphor",
    "cannabinol",
    "cantharidin",
    "carbamate",
    "carbostyril",
    "carbromal",
    "cardiotonic",
    "catechu",
    "cathine",
    "cevadine",
    "chelerythrine",
    "chinin",
    "chloral",
    "chloramphenicol",
    "chloroform",
    "chloroquine",
    "cholinergic",
    "cholinesterase",
    "cinchonidine",
    "cinchophen",
    "cineole",
    "cinnamaldehyde",
    "citrate",
    "clavacin",
    "cocaine",
    "codeine",
    "colchicine",
    "conquinine",
    "convulsant",
    "copal",
    "cortisone",
    "coumarin",
    "curare",
    "curcumin",
    "cycloplegic",
    "cymene",
    "cystamine",
    "diamorphine",
    "dicoumarin",
    "digitoxin",
    "ecstasy",
    "elecampane",
    "emend",
    "emetine",
    "ephedrine",
    "epinephrine",
    "epinine",
    "ergometrine",
    "ergonovine",
    "ergotamine",
    "ergotaminine",
    "erythrosin",
    "esculin",
    "estrogen",
    "ethylenediamine",
    "ethylmorphine",
    "eucaine",
    "eucalyptol",
    "eugenol",
    "excipient",
    "expectorant",
    "factive",
    "fenchone",
    "fibrinolysin",
    "flagroot",
    "flector",
    "forane",
    "gallotannin",
    "ginkgo",
    "ginseng",
    "glycyrrhizin",
    "goldenseal",
    "gonadotropin",
    "guaiac",
    "guanidine",
    "guvacine",
    "harmaline",
    "heparin",
    "heroin",
    "hexamethylenamine",
    "hexylresorcinol",
    "histamine",
    "hyaluronidase",
    "hydramine",
    "hydrochloride",
    "hydrogel",
    "hydroquinine",
    "hydroquinone",
    "hyoscine",
    "hyoscyamine",
    "hypericin",
    "hypoglycemic",
    "indazole",
    "indirubin",
    "insulin",
    "inula",
    "isatin",
    "isocodeine",
    "isomeride",
    "isorhodeose",
    "isoxazole",
    "karaya",
    "licorice",
    "lithium",
    "luminal",
    "lustral",
    "mannose",
    "marijuana",
    "methadone",
    "methemoglobin",
    "methenamine",
    "methylamine",
    "morphia",
    "morphine",
    "myrrh",
    "narcotic",
    "nikethamide",
    "nitroglycerin",
    "nitroprusside",
    "olibanum",
    "opium",
    "ouabain",
    "oxyquinoline",
    "oxytocic",
    "palladia",
    "paludrin",
    "paludrine",
    "papaverine",
    "paraderm",
    "paraldehyde",
    "parasiticide",
    "paregoric",
    "penicillin",
    "pentobarbital",
    "peppermint",
    "phenacetin",
    "phenazone",
    "phenetidine",
    "phenobarbital",
    "phenothiazine",
    "physostigmine",
    "picropodophyllin",
    "picrotoxin",
    "pilocarpine",
    "piperazine",
    "podophyllin",
    "propolis",
    "protamine",
    "pseudoephedrine",
    "pseudotropine",
    "psyllium",
    "pyrazole",
    "pyridoxine",
    "pyruvaldehyde",
    "quercetin",
    "quinacrine",
    "quinate",
    "quinazoline",
    "quinidine",
    "quinina",
    "quinine",
    "quinoxaline",
    "rattleroot",
    "rhein",
    "rotenone",
    "safrole",
    "salicylamide",
    "salix",
    "salol",
    "santonin",
    "scopolamine",
    "senega",
    "sinomenine",
    "snakeroot",
    "sparteine",
    "spasmolytic",
    "stilbestrol",
    "stilboestrol",
    "streptomycin",
    "strychnin",
    "strychnine",
    "sulfadiazine",
    "sulfaguanidine",
    "sulfamerazine",
    "sulfamethazine",
    "sulfamethylthiazole",
    "sulfanilamide",
    "sulfapyridine",
    "sulfaquinoxaline",
    "sulfathiazole",
    "sympatholytic",
    "sympathomimetic",
    "tenuate",
    "theophylline",
    "thiouracil",
    "thymol",
    "thymoquinone",
    "thyroglobulin",
    "tragacanth",
    "tramal",
    "trental",
    "trichloroethylene",
    "trinitrotoluene",
    "triterpene",
    "tryptophan",
    "tyramine",
    "usnea",
    "valerone",
    "vasoconstrictor",
    "vasodilator",
    "veratrine",
    "vermifuge",
    "wormwood",
    "xanthopterin",
    "yajeine",
    "yohimbine",
    "glycyrrhiza"
}

extra_terms_to_exclude_from_drugs_dictionary = {
    "black lead",
    "mineral carbon",
    "natural graphite",
    "whole blood",
    "oxygen therapy",
    "mandarin peel",
    "pomegranate fruit",
    "green tea",
    "gold leaf",
    "gold powder",
    "patent blue",
    "horse chestnut",
    "blue x",
    "dry ice",
    "macadamia nut",
    "brussels sprout",
    "beet sugar",
    "cane sugar",
    "table sugar",
    "white sugar",
    "kiwi fruit",
    "bilberry fruit",
    "bullhead fruit",
    "caltrop fruit",
    "tribulus fruit",
    "green tea",
    "pomegranate fruit",
    "schisandra fruit",
    "forsythia fruit",
    "garcinia fruit",
    "paraguay tea",
    "mace fruit",
    "nutmeg fruit",
    "cashew fruit",
    "java tea",
    "kidney tea",
    "g proteins",
    "johnson",
    "ligand",
    "ligands",
}

extra_terms_to_exclude_from_drugs_dictionary = extra_terms_to_exclude_from_drugs_dictionary.union(
    {
        'abbott',
        'abbvie',
        'abiomed',
        'abivax',
        'abraxis bioscience',
        'acadia',
        'acceleron',
        'acg group',
        'aci limited',
        'acme laboratories',
        'acorda',
        'actavis',
        'actelion',
        'acura',
        'adcock ingram',
        'advanz',
        'advaxis',
        'aerie',
        'agios',
        'ajanta',
        'akbarieh',
        'akorn',
        'alcon',
        'alembic',
        'alexion',
        'algeta',
        'alimera',
        'alk-abelló',
        'alkaloid',
        'alkem',
        'alkermes',
        'allen & hanburys',
        'allergan',
        'allozyne',
        'almirall',
        'alnylam',
        'alphapharm',
        'altana',
        'alvogen',
        'alzheon',
        'ambit',
        'ameridose',
        'amersham plc',
        'amgen',
        'amneal',
        'amphastar',
        'amylin',
        'anacor',
        'angelini',
        'angiotech',
        'annexin',
        'anthera',
        'antibe',
        'antibiotice iași',
        'antikamnia',
        'aplia',
        'apotex',
        'apothécure',
        'apricus',
        'aptalis',
        'arbutus',
        'arena',
        'ariad',
        'array',
        'arrowhead',
        'aryogen',
        'aspen pharmacare',
        'assertio',
        'astellas',
        'astex',
        'astra',
        'astrazeneca',
        'aurobindo',
        'aurora',
        'avella',
        'aventis',
        'ayrton',
        'b. braun',
        'barkat',
        'bausch & lomb',
        'bausch health',
        'bavarian nordic',
        'baxalta',
        'baxter',
        'bayer',
        'beacon',
        'beecham group',
        'behestan darou',
        'beigene',
        'benitec',
        'berlin chemie',
        'besins healthcare',
        'beximco',
        'bharat biotech',
        'bio farma',
        'biocon',
        'biocryst',
        'bioderma',
        'biogen',
        'bioinvent',
        'biolex',
        'biolinerx',
        'biomarin',
        'biomérieux',
        'biondvax',
        'bionova',
        'biotie therapies',
        'biovail',
        'bioverativ',
        'biovest',
        'biovista',
        'bliss',
        'block drug',
        'bluepharma',
        'boehringer mannheim',
        'bosnalijek',
        'bracco',
        'bradley',
        'british biotech',
        "buckley's",
        'cadila',
        'camurus',
        'cancervax',
        'cangene',
        'cansinobio',
        'capsugel',
        'carefusion',
        'cassava sciences',
        'catalent',
        'catalyst',
        'cathay drug',
        'cederroth',
        'cel-sci',
        'celesio',
        'celgene',
        'celltech',
        'celltrion',
        'cencora',
        'century',
        'cephalon',
        'ceragenix',
        'cerevel',
        'chemidex',
        'cheng fong',
        'chiesi',
        'chiron corporation',
        'chiroscience',
        'chong kun dang',
        'chugai',
        'cinnagen',
        'cipla',
        'civica rx',
        'clovis oncology',
        'cobel darou',
        'combe',
        'compugen',
        'concord',
        'corcept',
        'covidien',
        'creative biomart',
        'crookes healthcare',
        'crucell',
        'csl behring',
        'cspc zhongrun',
        'cubist',
        'curevac',
        'cutter',
        'cyclacel',
        'cynapsus',
        'cytokinetics',
        'cytrx',
        'dabur',
        'daewoong',
        'daiichi sankyo',
        'danco',
        'darou pakhsh',
        'debiopharm',
        'dechra',
        'delix',
        'dentsply sirona',
        'dermapharm',
        'deurali-janta',
        'diamyd medical',
        'diffusion',
        'distillers',
        "divi's laboratories",
        'douglas',
        'editas medicine',
        'eisai',
        'elder',
        'emcure',
        'emergent',
        'empire',
        'endocyte',
        'eskayef',
        'esperion',
        'esteve',
        'exelgyn',
        'f. h. faulding & co',
        'fabre-kramer',
        'fareva',
        'farmitalia',
        'faron',
        'fermentek',
        'ferring',
        'fisons',
        'flavorx',
        'flexion',
        'forest',
        'fortress',
        'fortune pharmacal',
        'fosun',
        'fresenius',
        'fulhold',
        'g.d. searle',
        'g.f. harvey company',
        'galapagos nv',
        'galderma',
        'galena',
        'galenika',
        'gedeon richter',
        'genentech',
        'general',
        'genetics institute',
        'genmab',
        'genset',
        'genzyme',
        'giaconda',
        'gilead',
        'glatt group',
        'glaxosmithkline',
        'glenmark',
        'gpc biotech',
        'graceway',
        'granules india',
        'green cross',
        'grifols',
        'grindeks',
        'grünenthal',
        'guangzhou',
        'h. k. mulford',
        'hafslund nycomed',
        'hal allergy group',
        'hanhong',
        'hanmi',
        'hansoh',
        'harbin',
        'harrow health',
        'help remedies',
        'herron',
        'hetero drugs',
        'hikma',
        'himispherx',
        'hisamitsu',
        'hoechst',
        'horizon',
        'hospira',
        'hovid',
        'hovione',
        'huadong medicine',
        'hypera',
        'immunogen',
        'immunomedics',
        'immuron',
        'immutep',
        'incepta',
        'incyte',
        'insys',
        'intarcia',
        'intas',
        'ionis',
        'ipsen',
        'jaber ebne hayyan',
        'janssen',
        'jenapharm',
        'jennerex',
        'jerini',
        'jiangsu hengrui',
        'johnson & johnson',
        'jointown',
        'jones',
        'julphar',
        'kadmon',
        'kalbe farma',
        'kamada',
        'kangmei',
        'kannalife',
        'kimia farma',
        'kinetic concepts',
        'kissei',
        'knight',
        'knoll',
        'kunming',
        'kyowa kirin',
        'laurus labs',
        'lavipharm',
        'lawley',
        'leadiant',
        'lexicon',
        'lifse',
        'ligand',
        'lijun',
        'liminal',
        'locus',
        'loghman',
        'lundbeck',
        'lundbeck seattle',
        'lupin limited',
        'mallinckrodt',
        'mankind',
        'marathon',
        'martek',
        'martin dow',
        'massone',
        'maxygen',
        'mayne',
        'mcguff',
        'medac',
        'medarex',
        'medherant',
        'medimmune',
        'medivation',
        'medivir',
        'medochemie',
        'meiji seika',
        'melinta',
        'melior discovery',
        'menarini',
        'mentholatum',
        'merck & co.',
        'merck group',
        'merrimack',
        'meyer brothers',
        'microgen',
        'miles laboratories',
        'mindmed',
        'mitsubishi tanabe',
        'mochida',
        'moderna',
        'molecular partners',
        'movetis',
        'mundipharma',
        'mustang',
        'mylan',
        'myrexis',
        'myriad genetics',
        'naari',
        'nanjing ange',
        'natco',
        'nativita',
        'nector',
        'neilmed',
        'neimeth',
        'nektar',
        'nereus',
        'neurolixis',
        'neuropathix',
        'nicox',
        'nippon kayaku',
        'nippon soda',
        'north china',
        'novabay',
        'novartis',
        'novavax',
        'novo nordisk',
        'novobiotic',
        'noxxon',
        'nuvelo',
        'nycomed',
        'ocean biomedical',
        'octapharma',
        'olainfarm',
        'omega',
        'oncolytics',
        'opsona',
        'oramed',
        'orchid',
        'orexigen',
        'orexo',
        'organon & co.',
        'orifarm',
        'orion',
        'ortho',
        'ortho-mcneil',
        'otis clapp',
        'otsuka',
        'ovation',
        'oxford biomedica',
        'oystershell nv',
        'painceptor',
        'panacea biotec',
        'parke-davis',
        'patheon',
        'perrigo',
        'perseidjv',
        'pfizer',
        'pfizer uk',
        'pharma nord',
        'pharmacia',
        'pharmacia & upjohn',
        'pharmacosmos',
        'pharmaniaga',
        'pharmascience',
        'pharmavite',
        'pharmstandard',
        'photocure',
        'piramal group',
        'pku healthcare',
        'plexxikon',
        'pliva',
        'pluri',
        'portola',
        'poulenc frères',
        'powderject',
        'prasco',
        'precision',
        'procter & gamble',
        'profound',
        'promomed',
        'proqr',
        'protalix',
        'protein sciences',
        'protek',
        'proteolix',
        'proteon',
        'psivida',
        'purdue',
        'quantum',
        'quark',
        'r-pharm',
        'ratiopharm',
        'reata',
        'reckitt',
        'recursion',
        'regeneron',
        'regulus',
        'reliant',
        'renata',
        'renovo',
        'repligen',
        'repros',
        'retrotope',
        'rhône-poulenc',
        'roche',
        'rohto',
        'romat',
        'rosepharma',
        'roussel uclaf',
        'rowell',
        'rubicon research',
        'ryukakusan',
        's. e. massengill',
        'saidal',
        'salix',
        'salubris',
        'sangamo',
        'sanitas',
        'sankogan',
        'sanofi',
        'sanofi pasteur',
        'santaris',
        'santen',
        'sarepta',
        'schering ag',
        'schering-plough',
        'scioderm',
        'seagen',
        'seppic',
        'serono',
        'servier',
        'shanghai',
        'sheffield',
        'shenzhen kangtai',
        'shionogi',
        'shire',
        'sido muncul',
        'sigma healthcare',
        'sihuan',
        'silence',
        'simcere',
        'sinopharm',
        'sinopharm group',
        'sinovac',
        'smnith',
        'solopharm',
        'solvay',
        'somnogen canada inc',
        'spark',
        'spectrum',
        'sphere fluidics',
        'square',
        'stada arzneimittel',
        'stallergenes greer',
        'starwin',
        'sterling',
        'stiefel',
        'strides',
        'stryker',
        'sucampo',
        'sumitomo',
        'sumitomo chemical',
        'sunovion',
        'sutro',
        'syntex',
        'synthon',
        'taisho',
        'takeda',
        'tanox',
        'tasly',
        'teijin',
        'telesta',
        'temmler',
        'terapia ranbaxy',
        'teva canada',
        'theramex',
        'theraplix',
        'thornton & ross',
        'tibotec',
        'tilray',
        'tonix',
        'torque',
        'torrent',
        'transgene',
        'troikaa',
        'trubion',
        'ttk group',
        'turing',
        'unichem',
        'unilab',
        'unilever',
        'upjohn',
        'vectura',
        'veloxis',
        'veranova',
        'vernalis group',
        'vernalis plc',
        'vernalis research',
        'vertex',
        'vianex',
        'viatris',
        'viiv healthcare',
        'viromed',
        'viropharma',
        'vivimed labs',
        'warner chilcott',
        'warner-lambert',
        'weifa',
        'wilson therapeutics',
        'wockhardt',
        'wuxi apptec',
        'wyeth',
        'wörwag',
        'xiangxue',
        'yangtze river',
        'yuhan',
        'yunnan baiyao group',
        'zambon',
        'zandu realty',
        'zealand',
        'zeneca',
        'zentiva',
        'zeria',
        'zoetis',
        'zonite',
        'zydus',
        'zymeworks',
        'zymogenetics'}
)

extra_mappings = {"mounjaro": "tirzepatide"}
